baseurl = "/"
languageCode = "en-us"
title = "An Chu's data blog"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Codes"
    url = "https://github.com/chuvanan"

[params]
    description = "There is no safety in numbers, or in anything else."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "lisp"]
    highlightjsTheme = "zenburn"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "emacs-logo.png"
    width = 50
    height = 50
    alt = "Logo"
