baseurl = "/"
languageCode = "en-us"
title = "An Chu's data blog"
theme = "hugo-xmin"
googleAnalytics = "UA-120197914-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "Codes"
    url = "https://github.com/chuvanan"
    weight = 3

[params]
    description = "There is no safety in numbers, or in anything else."
    footer = "&copy; An Chu 2017 -- 2018 | Theme: [hugo-xmin](https://github.com/yihui/hugo-xmin) | Built by [blogdown](https://github.com/rstudio/blogdown)"

    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com"
    highlightjsLang = ["r", "yaml", "lisp", "bash"]
    highlightjsTheme = "github"
